# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: "%ez_sylius.shop_path_prefix%"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: "%ez_sylius.shop_admin_path_prefix%"

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: "%ez_sylius.shop_api_path_prefix%"
